apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service  # Nama Service yang akan digunakan
  labels:
    app: backend  # Label yang akan diberikan pada Service
spec:
  type: NodePort  # Jenis Service yang akan digunakan (NodePort)
  ports:
  - port: 8080  # Port yang akan diexpose oleh Service
  selector:
    app: backend  # Selector untuk memilih Pod yang memiliki label "app: backend"
