apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-backend  # Nama Deployment yang akan digunakan
spec:
  replicas: 1  # Jumlah replika yang akan dibuat untuk Deployment ini
  selector:
    matchLabels:
      app: backend  # Selector untuk memilih Pod yang memiliki label "app: backend"
  template:
    metadata:
      labels:
        app: backend  # Label yang akan diberikan pada Pod yang dibuat
    spec:
      containers:
      - name: karsajobs  # Nama container
        image: ghcr.io/zaelani23/karsajobs:latest  # Image Docker yang akan digunakan untuk container ini
        imagePullPolicy: Always  # Kebijakan untuk menarik image, selalu menarik image terbaru
        ports:
        - containerPort: 8080  # Port yang akan diexpose oleh container
        env:
          - name: APP_PORT  # Variable environment untuk menentukan port aplikasi
            value: "8080"  # Nilai dari variable environment APP_PORT
          - name: MONGO_HOST  # Variable environment untuk menentukan host MongoDB
            value: mongo-service  # Nilai dari variable environment MONGO_HOST
          - name: MONGO_USER  # Variable environment untuk menentukan pengguna MongoDB
            valueFrom:
              secretKeyRef:
                name: mongo-credentials  # Nama secret yang berisi kredensial MongoDB
                key: MONGO_ROOT_USERNAME  # Kunci di dalam secret untuk mendapatkan nilai dari variable environment MONGO_USER
          - name: MONGO_PASS  # Variable environment untuk menentukan kata sandi MongoDB
            valueFrom:
              secretKeyRef:
                name: mongo-credentials  # Nama secret yang berisi kredensial MongoDB
                key: MONGO_ROOT_PASSWORD  # Kunci di dalam secret untuk mendapatkan nilai dari variable environment MONGO_PASS
