apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service  # Nama Deployment yang akan digunakan
spec:
  replicas: 1  # Jumlah replika yang akan dibuat untuk Deployment ini
  selector:
    matchLabels:
      app: shipping-service  # Selector untuk memilih Pod yang memiliki label "app: shipping-service"
  template:
    metadata:
      labels:
        app: shipping-service  # Label yang akan diberikan pada Pod yang dibuat
    spec:
      containers:
      - name: shipping-service  # Nama container
        image: ghcr.io/zaelani23/shipping-service:latest  # Image Docker yang akan digunakan untuk container ini
        imagePullPolicy: Always  # Kebijakan untuk menarik image, selalu menarik image terbaru
        ports:
        - containerPort: 3001  # Port yang akan diexpose oleh container
        env:
          - name: PORT  # Variable environment untuk menentukan port aplikasi
            value: "3001"  # Nilai dari variable environment PORT
          - name: AMQP_URL
            value: "amqp://localhost:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service  # Nama Service yang akan digunakan
  labels:
    app: shipping-service  # Label yang akan diberikan pada Service
spec:
  type: NodePort  # Jenis Service yang akan digunakan (NodePort)
  ports:
  - port: 3001  # Port yang akan diexpose oleh Service
  selector:
    app: shipping-service  # Selector untuk memilih Pod yang memiliki label "app: shipping-service"